[project]
name = "local-chatbox"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.17.1",
    "openai>=1.64.0",
    "pywebview>=5.4",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.12.0",
    "pywin32-ctypes>=0.2.3",
]
